### ISSUE TITLE
question about some details in vgmidi_raw_1.json file

### ISSUE THREAD

**Issue by TwinMooon** [lucasnfe/vgmidi#1]
- There have 32 time-series of valence and arousal, which indicated 30 in paper.
 And where is the spitting point,or time step, for each chunk? In other words, what's the duration of the chunk corresponding to the first or another valence value?
- There have 2 valence-related key for each element, "ex1_valence"  and "ex2_valence" , what's the difference between them? 
- Does the name "piece0_11" mean the annotation labeled by subject 11 for piece 0?
Thank you, and I look forward to your reply

**Comment by jbmaxwell** [comment]
@TwinMooon, did you manage to figure out the formatting of the json files? I'm also interested in the raw data, but not sure how to interpret the format. My main question, I think, is how to interpret the 30 segments (as you mention), but also what each float in the "arousal" and "valence" vectors corresponds to. Since the number of values in each vector varies across segments, but is the same for "arousal" and "valence", I'm assuming these are either groupings of events with the same onset, or some other time slice.

UPDATE: Hmm... I was just thinking that maybe the arousal/valence vectors are just the number of events you get from splitting the whole piece into 30 segments? So it's not based on a metric division, like bars/beats, per se, but just dividing the whole piece into 30 segments? @lucasnfe, is that how it works?

**Comment by TwinMooon** [comment]
@jbmaxwell each scalar in the arousal or valence vector denotes the annotation of a measure in the piece. And the size of each vector is different because the length of each piece is different.

**Comment by jbmaxwell** [comment]
Ah, okay, thanks! So, sorting by the `_n` suffix and concatenating the vectors should give us the total timeline of annotations, in measures. Correct? ...e.g., `piece1_1 valence + piece1_2 valence ...`

**Comment by jbmaxwell** [comment]
I'm noticing my previous assumption was kinda dumb, because these are different subjects...
What I'd ideally like to get is the sequence of ratings, per measure, per piece, for each subject—e.g., so I can get an average valence/arousal for a given bar, in a given midi file.

UPDATE: Ah, I think I get it now... 32 subjects, _n_ valence/arousal values each, where _n_ is the number of bars. I had misread the piece->annotation mapping on one example, so the indicated "measures" wasn't matching the vector length... that's what confused me. I see now that "measures" does match the vector length for each one. Sorry for the spam (but let me know if I'm still stupid! Haha.)

**Comment by TwinMooon** [comment]
@jbmaxwell 
All pieces have converted to the form that a quarter note is a beat and 4 quarter notes form a bar.

[reference 1](https://github.com/lucasnfe/adl-music-annotation/blob/d1fba8d4a3ec8c2d7f5488507441ce31cdb807d6/js/annotation/annotation-controller.js#L111)
[reference 2](https://github.com/lucasnfe/adl-music-annotation/blob/d1fba8d4a3ec8c2d7f5488507441ce31cdb807d6/py/midi2annotation/midi2annotation.py#L11)
